import numpy as np
import os
import glob
import csv

exe_name = 'heisenberg'


def run(omega, N, eta, max_iter, tol, i, j, maxm, cut):

    """Run the executable generated by the C++ file"""

    os.system("./{} {} {} {} {} {} {} {} {} {}".format(exe_name, omega, N, eta, max_iter, tol, i, j, maxm, cut))


omega = np.linspace(start=-1., stop=4., num=200, dtype=float)
correlator = []

# Loop over energies
for o in omega:

    run(omega=o, N=5, eta=0.05, max_iter=50, tol=1E-5, i=1, j=1, maxm=20, cut=1E-6)


# Sort the filenames numerically
filenames = sorted([(element[len(exe_name)+6:-4]) for element in glob.glob('data/*.txt')], key=float)


# Read result form files and delete intermediate files
for filename in filenames:

    name = 'data/{}_{}.txt'.format(exe_name, filename)
    f = open(name)
    correlator.append(float(f.readline()))
    f.close()
    os.remove(name)


# Save data in final file
f = open('data/{}_data.csv'.format(exe_name), 'w')
out = csv.writer(f, delimiter=' ')
out.writerows(zip(omega, correlator))
f.close()
